# Generated by Django 2.2.1 on 2019-05-31 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('session_id', models.CharField(max_length=255)),
                ('user', models.CharField(default='Anonymous', max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('belonging_team', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
