# Generated by Django 2.2.1 on 2019-06-01 09:55

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('identification', models.CharField(default=home.models.generateID, max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('app_type', models.CharField(choices=[('EDU', 'Education')], max_length=5, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('belonging_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team')),
            ],
        ),
    ]
