# Generated by Django 2.2.1 on 2019-06-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('belongs', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=50)),
                ('bw_id', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=30)),
                ('attend', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
